github workflow for arm images 3

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,6 +26,14 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
+      - name: Debug Yarn and Environment
+        run: |
+          yarn --version || echo "Yarn not installed"
+          node --version || echo "Node not installed"
+          echo "Current working directory: $(pwd)"
+          echo "Contents of node_modules:"
+          ls -al node_modules || echo "node_modules directory not found"
+
       - name: Determine Docker tag
         id: docker_tag
         run: |
@@ -34,9 +42,6 @@ jobs:
           else
             echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
           fi
-
-      - name: Debug Docker tag
-        run: echo "Docker tag is ${{ env.tag }}"
 
       - name: Build and push Docker image (ARM)
         uses: docker/build-push-action@v5
